openapi: 3.0.1

info:
  title: Social network
  description: Current API describes interaction with travel Social network
  version: 1.0.0

paths:
  /social-network/user/{user_gid}/post-management:
    post:
      summary: Create post
      description: Method creates user post
      tags:
        - Post
      parameters:
        - name: user_gid
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: Post title
                description:
                  type: string
                  description: Post description
                images:
                  type: array
                  description: Post images
                  items:
                    type: string
                    format: binary
                location:
                  $ref: "#/components/schemas/Location"
              required:
                - user_gid
                - title
                - location
            examples:
              request:
                value:
                  title: "Paris"
                  description: "Walking in Paris"
                  images: ["/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBwgHBgkIBwgKCgkLDRYPDQwMDRsUFRAWIB0iIiAdHx8kKDQsJCYxJx8fLT0tM"]
                  location:
                    latitude: 37.7749
                    longitude: -122.4194
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  post_gid:
                    type: string
                    description: id of user post
                  created_at:
                    type: string
                    format: date-time
                    description: Post creation date
                required:
                  - post_gid
                  - created_at
              examples:
                response:
                  value:
                    post_gid: "cf8d5b9e-29f8-4834-8b9d-dd831c70ec05"
                    created_at: "2019-08-24 21:15:22"
        400:
          description: Bad Request
        500:
          description: Server error
  /social-network/user/{user_gid}/posts:
    get:
      summary: Get posts
      description: Method get user posts
      tags:
        - Post
      parameters:
        - name: user_gid
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Post'
              examples:
                response:
                  value:
                    - post_gid: "cf8d5b9e-29f8-4834-8b9d-dd831c70ec05"
                      created_at: "2019-08-24 21:15:22"
                      images: ["/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBwgHBgkIBwgKCgkLDRYPDQwMDRsUFRAWIB0iIiAdHx8kKDQsJCYxJx8fLT0tM"]
                      location:
                        latitude: 37.7749
                        longitude: -122.4194
                      comments:
                        - comment_gid: "er8d5b9e-29f8-4834-8b9d-dd831c70ec05"
                          user_gid: "rt8d5b9e-29f8-4834-8b9d-dd831c70ec05"
                          text: "Impressive!"
                          created_at: "2019-08-24 22:15:22"
                          likes: 5
                          dislikes: 2
                      likes:
                        - "rt8d5b9e-29f8-4834-8b9d-dd831c70ec05"
                      dislikes:
                        - "gh8d5b9e-29f8-4834-8b9d-dd831c70ec05"
        400:
          description: Bad Request
        500:
          description: Server error
  /social-network/post-management/{post_gid}:
    put:
      summary: Update post
      description: Method update user post
      tags:
        - Post
      parameters:
        - name: post_gid
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_gid:
                  type: string
                  description: User GID
                title:
                  type: string
                  description: Post title
                description:
                  type: string
                  description: Post description
                images:
                  type: array
                  description: Post images
                  items:
                    type: string
                    format: binary
                location:
                  $ref: "#/components/schemas/Location"
              required:
                - user_gid
            examples:
              request:
                value:
                  user_gid: "29acbce4-a68d-4612-8667-e89b87bdf368"
                  title: "Minsk"
                  description: "Walking in Minsk"
                  images: ["/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBwgHBgkIBwgKCgkLDRYPDQwMDRsUFRAWIB0iIiAdHx8kKDQsJCYxJx8fLT0tM"]
                  location:
                    latitude: 37.7749
                    longitude: -122.4194
      responses:
        200:
          description: Ok
        400:
          description: Bad Request
        500:
          description: Server error
    delete:
      summary: Delete post
      description: Method delete user post
      tags:
        - Post
      parameters:
        - name: post_gid
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Ok
        400:
          description: Bad Request
        500:
          description: Server error
  /social-network/user/{user_gid}/comment-management:
    post:
      summary: Create comment
      description: Method creates user comment at the post
      tags:
        - Comment
      parameters:
        - name: user_gid
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                post_gid:
                  type: string
                  description: Post gid
                text:
                  type: string
                  description: Comment text
              required:
                - post_gid
                - text
            examples:
              request:
                value:
                  post_gid: "cf8d5b9e-29f8-4834-8b9d-dd831c70ec05"
                  text: "Super"
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  comment_gid:
                    type: string
                    description: GID of user comment
                  created_at:
                    type: string
                    format: date-time
                    description: Comment creation date
                required:
                  - comment_gid
                  - created_at
              examples:
                response:
                  value:
                    comment_gid: "cf8d5b9e-29f8-4834-8b9d-dd831c70ec05"
                    created_at: "2019-08-24 21:15:22"
        400:
          description: Bad Request
        500:
          description: Server error
  /social-network/post/{post_gid}/comment-management/comments:
    get:
      summary: Get commentss
      description: Method get post comments
      tags:
        - Comment
      parameters:
        - name: post_gid
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Comment'
              examples:
                response:
                  value:
                    - comment_gid: "cf8d5b9e-29f8-4834-8b9d-dd831c70ec05"
                      user_gid: "vb8d5b9e-29f8-4834-8b9d-dd831c70ec05"
                      created_at: "2019-08-24 21:15:22"
                      text: "qwewqe"
                      likes:
                        - "rt8d5b9e-29f8-4834-8b9d-dd831c70ec05"
                      dislikes:
                        - "gh8d5b9e-29f8-4834-8b9d-dd831c70ec05"
        400:
          description: Bad Request
        500:
          description: Server error
  /social-network/comment-management/{comment_gid}:
    put:
      summary: Update comment
      description: Method update user comment
      tags:
        - Comment
      parameters:
        - name: comment_gid
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_gid:
                  type: string
                  description: User GID
                text:
                  type: string
                  description: Comment text
              required:
                - user_gid
                - text
            examples:
              request:
                value:
                  user_gid: "29acbce4-a68d-4612-8667-e89b87bdf368"
                  text: "Cool"
      responses:
        200:
          description: Ok
        400:
          description: Bad Request
        500:
          description: Server error
    delete:
      summary: Delete comment
      description: Method delete user comment
      tags:
        - Comment
      parameters:
        - name: comment_gid
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Ok
        400:
          description: Bad Request
        500:
          description: Server error
  /social-network/posts:
    get:
      summary: Get posts by location
      description: Method get posts by location
      parameters:
        - name: latitude
          in: query
          required: true
          schema:
            type: number
            format: float
          example: 37.7749
        - name: longitude
          in: query
          required: true
          schema:
            type: number
            format: float
          example: -122.4194
      tags:
        - Post
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Post'
              examples:
                response:
                  value:
                    - post_gid: "cf8d5b9e-29f8-4834-8b9d-dd831c70ec05"
                      created_at: "2019-08-24 21:15:22"
                      images: ["/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBwgHBgkIBwgKCgkLDRYPDQwMDRsUFRAWIB0iIiAdHx8kKDQsJCYxJx8fLT0tM"]
                      location:
                        latitude: 37.7749
                        longitude: -122.4194
                      comments:
                        - comment_gid: "er8d5b9e-29f8-4834-8b9d-dd831c70ec05"
                          user_gid: "rt8d5b9e-29f8-4834-8b9d-dd831c70ec05"
                          text: "Impressive!"
                          created_at: "2019-08-24 22:15:22"
                          likes: 5
                          dislikes: 2
                      likes:
                        - "rt8d5b9e-29f8-4834-8b9d-dd831c70ec05"
                      dislikes:
                        - "gh8d5b9e-29f8-4834-8b9d-dd831c70ec05"
        400:
          description: Bad Request
        500:
          description: Server error
components:
  schemas:
    Location:
      type: object
      description: Geographical location data
      properties:
        latitude:
          type: number
          format: float
          description: Latitude of the location
          example: 37.7749
        longitude:
          type: number
          format: float
          description: Longitude of the location
          example: -122.4194
    Post:
      type: object
      properties:
        post_gid:
          type: string
          description: Gid of user post
        created_at:
          type: string
          format: date-time
          description: Post creation date
        images:
          type: array
          description: Post images
          items:
            type: string
            format: binary
        location:
          $ref: "#/components/schemas/Location"
        likes:
          type: array
          description: Post likes number
          items:
            type: string
            description: User GID
        dislikes:
          type: array
          description: Post dislikes number
          items:
            type: string
            description: User GID
        comments:
          $ref: "#/components/schemas/Comment"
      required:
        - post_gid
        - created_at
        - images
        - location
        - likes
        - dislikes
        - comments
    Comment:
      type: object
      properties:
        comment_gid:
          type: string
          description: Gid of user comment
        user_gid:
          type: string
          description: User GID
        text:
          type: string
          description: Gid of user post
        created_at:
          type: string
          format: date-time
          description: Comment creation date
        likes:
          type: array
          description: Post likes number
          items:
            type: string
            description: User GID
        dislikes:
          type: array
          description: Post dislikes number
          items:
            type: string
            description: User GID
      required:
        - comment_gid
        - user_gid
        - text
        - created_at
        - likes
        - dislikes